name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image
      run: |
        docker build . --tag ghcr.io/watchcathq/watchcat-docs:build_${{ github.run_number }}
        docker push ghcr.io/watchcathq/watchcat-docs:build_${{ github.run_number }}
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: watchcat
        SLACK_COLOR: ${{ job.status }}
        SLACK_MESSAGE: 'Docker image for ${{ github.event.repository.name }} has been built :rocket:'
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
